name: Auto Merge Dependabot Pull Requests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && github.event.pull_request.merged == false
    steps: 
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Run Build
        run: bun install

      - name: Merge Pull Requests
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            gh pr merge ${{ github.event.pull_request.number }} --squash --admin
          
        
        
